### ISSUE TITLE
`panic: runtime error: invalid memory address or nil pointer dereference` on invalid slugs

### ISSUE THREAD

**Issue by MestreLion** [bdd/runitor#41]
```console
$ HC_PING_KEY=... runitor -slug nonexisting -- echo testing
2022/06/05 12:28:32 PingStart: nonretriable error response: 404 Not Found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x626935]

goroutine 1 [running]:
main.Do({0xc000010280, 0x2, 0x2}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x2710}, {0xc00001c2e0, ...}, ...)
	bdd.fi/x/runitor/cmd/runitor/main.go:242 +0x115
main.main.func4(...)
	bdd.fi/x/runitor/cmd/runitor/main.go:206
main.main()
	bdd.fi/x/runitor/cmd/runitor/main.go:209 +0xbf3
```
When using a valid slug it works fine

`runitor-v0.10.0-linux-amd64`, pre-compiled binary downloaded from github releases

**Comment by bdd** [comment]
Sorry about this. Will cut a 0.10.1 release soon.

**Comment by bdd** [comment]
v0.10.1 is out https://github.com/bdd/runitor/releases/tag/v0.10.1

Thank you for your report.
